### ISSUE TITLE
callbacks.call example doesn't work

### ISSUE THREAD

**Issue by ceineke** [cujojs/when#460]
```
$ node --version
v0.10.35
```

```
var callbacks = require("when/callbacks");
var waitFiveSeconds = callbacks.call(setTimeout, 5000);
timers.js:219
      callback.apply(timer, args);
               ^
TypeError: Object 5000 has no method 'apply'
    at timer._onTimeout (timers.js:219:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by briancavalier** [comment]
Thanks, @ceineke. I'll take a look.

**Comment by briancavalier** [comment]
Yep, that example is pretty bone-headed ... who wrote that?!? :D  I'll add a better one soon

**Comment by briancavalier** [comment]
See #461
