### ISSUE TITLE
Usage hello world example fails with TypeError

### ISSUE THREAD

**Issue by john-aws** [cujojs/when#497]
The home page includes a hello world example using rest. That example fails to run (when@3.7.8, rest@2.0.0, node v6.10.3), as follows:

        .done(function(greeting) {
         ^
    
    TypeError: fetchRemoteGreeting(...).then(...).catch(...).done is not a function
        at Object.<anonymous> (/Users/test/test-when.js:6:6)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.runMain (module.js:604:10)
        at run (bootstrap_node.js:390:7)
        at startup (bootstrap_node.js:150:9)
        at bootstrap_node.js:505:3

**Comment by rkaw92** [comment]
Hi, I think `rest` uses native Promises, which do not support `.done()`. Not sure about the example - maybe at one point `rest` depended on the `when` Promise implementation? The code in the snippet indeed does not work.

(In this case, if you do intend to actually run it, you'd need to wrap the rest call in `when()`.)

**Comment by briancavalier** [comment]
@john-aws tl;dr Thanks for the heads up.  I'll fix the example.

Yes, @rkaw92 is correct.  In version 1.x, rest.js used when internally.  In 2.x, it uses native promises.  You can always convert from other promises to a when promise using the `when()` function: `const whenPromise = when(otherPromise)`.

**Comment by briancavalier** [comment]
Fixed by 47c5044c7cc2039b45471d602c4a0da587bd3788
